apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bottleneck-resolve-pdb
  namespace: bottleneck-resolve
  labels:
    app: bottleneck-resolve
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: bottleneck-resolve
