apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bottleneck-resolve

resources:
  - 01-namespace.yaml
  - 02-configmap.yaml
  - 03-secret.yaml
  - 11-serviceaccount.yaml
  - 12-rbac.yaml
  - 04-deployment.yaml
  - 05-service.yaml
  - 06-hpa.yaml
  - 07-pdb.yaml
  - 08-servicemonitor.yaml
  - 09-ingress.yaml
  - 10-networkpolicy.yaml

commonLabels:
  app: bottleneck-resolve
  managed-by: kustomize
